# Generated by Django 4.2.30 on 2026-06-29 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=150)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('origin', models.CharField(default='Virudhunagar', max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('pickup_address', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('parcel_type', models.CharField(blank=True, default='Documents', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('priority', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='COD', max_length=20)),
                ('booked_date', models.DateField(default=django.utils.timezone.now)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.customer')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='core.shipment')),
            ],
            options={
                'db_table': 'tracking_events',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Operations', 'Operations'), ('Delivery', 'Delivery'), ('Warehouse', 'Warehouse'), ('Support', 'Support')], default='Delivery', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on-leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account, if this staff member has dashboard access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'db_table': 'staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.staff'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank to show to all dashboard users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
