# Generated by Django 4.2.30 on 2026-06-30 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='booked_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
